# Usa un'immagine di base di Python
FROM python:3.9

# Aggiorna il sistema e installa SQLite
RUN apt-get update \
    && apt-get install -y sqlite3 \
    && rm -rf /var/lib/apt/lists/*


# Imposta la directory di lavoro nell'immagine Docker
WORKDIR /app

# Copia il tuo file db.sqlite3 nella directory di lavoro dell'immagine Docker
COPY db.sqlite3 /app/db.sqlite3
