name: ppm-project
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: "db-sqlite:latest"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
