# Generated by Django 4.2.1 on 2023-06-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollsAPI', '0003_choice_users_delete_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
