# Generated by Django 4.2.1 on 2023-06-14 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollsAPI', '0004_alter_poll_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='users',
        ),
        migrations.AddField(
            model_name='choice',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(),
        ),
    ]
