# Generated by Django 4.2.1 on 2023-06-09 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollsAPI', '0007_remove_poll_users_alter_poll_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
